# Generated by Django 5.2.8 on 2025-11-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('escola', models.CharField(max_length=200)),
                ('status_aluno', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('PENDENTE_RENOVACAO', 'Pendente Renovação')], default='ATIVO', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
