# Generated by Django 5.2.8 on 2025-11-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacional', '0002_aluno_user_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_validade_cadastro',
            field=models.DateField(blank=True, help_text='Data para renovação semestral', null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='declaracao_escolar',
            field=models.FileField(blank=True, null=True, upload_to='declaracoes_escolares/'),
        ),
    ]
