# Generated by Django 5.2.8 on 2025-11-21 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='placa do veiculo')),
                ('modelo', models.CharField(max_length=50, verbose_name='modelo do veiculo (exemplo: onibus, van, carro)')),
                ('capacidade', models.PositiveIntegerField(verbose_name='capacidade de passageiros')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.motorista', verbose_name='motorista responsavel pelo veiculo')),
            ],
            options={
                'verbose_name': 'veiculo',
                'verbose_name_plural': 'veiculos',
            },
        ),
    ]
