# Generated by Django 5.2.8 on 2025-11-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={},
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='motorista',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
