# Generated by Django 5.2.8 on 2025-11-21 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacional', '0001_initial'),
        ('rotas', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='checklist',
            name='alunos_presentes',
            field=models.ManyToManyField(blank=True, related_name='presencas', to='educacional.aluno'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.motorista'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALUNO_AUSENTE', 'Aluno Confirmou mas não Embarcou'), ('PROBLEMA_MECANICO', 'Problema Mecânico no Veículo'), ('ATRASO', 'Atraso na Rota'), ('OUTRO', 'Outro')], max_length=30)),
                ('descricao', models.TextField(help_text='Descreva o problema ou liste os alunos faltantes')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rotas.checklist')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.motorista')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmacaoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateField()),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educacional.aluno')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotas.rota')),
            ],
            options={
                'verbose_name': 'Confirmação de Viagem',
                'verbose_name_plural': 'Confirmações de Viagem',
                'unique_together': {('aluno', 'rota', 'data_viagem')},
            },
        ),
    ]
