# Generated by Django 5.2.8 on 2025-11-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0002_remove_checklist_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='horario_inicio',
            field=models.TimeField(blank=True, help_text='Horário de saída do ponto inicial', null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='prazo_limite_confirmacao',
            field=models.TimeField(blank=True, help_text='Horário limite para o aluno confirmar', null=True),
        ),
    ]
