# Generated by Django 5.2.8 on 2025-11-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0003_rota_horario_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='horario_inicio',
            field=models.TimeField(default='09:00', help_text='Horário de saída do ponto inicial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rota',
            name='prazo_limite_confirmacao',
            field=models.TimeField(default='12:00', help_text='Horário limite para o aluno confirmar'),
            preserve_default=False,
        ),
    ]
