# Generated by Django 5.2.8 on 2025-11-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0004_alter_rota_horario_inicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmacaoviagem',
            options={},
        ),
    ]
