# Generated by Django 5.2.8 on 2025-11-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0005_alter_confirmacaoviagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacaoviagem',
            name='tipo',
            field=models.CharField(choices=[('IDA', 'Ida'), ('VOLTA', 'Volta'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=10),
        ),
    ]
