# Generated by Django 5.2.8 on 2025-11-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0006_confirmacaoviagem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacaoviagem',
            name='tipo',
            field=models.CharField(choices=[('IDA', 'Ida'), ('VOLTA', 'Volta')], default='IDA', max_length=10),
        ),
    ]
