# Generated by Django 5.2.8 on 2025-11-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacional', '0003_aluno_data_validade_cadastro_and_more'),
        ('rotas', '0007_alter_confirmacaoviagem_tipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='confirmacaoviagem',
            unique_together={('aluno', 'rota', 'data_viagem', 'tipo')},
        ),
    ]
